main_project/SpockPrices_webapp/src/main/java/org/spockprices/app/mbeans/HelloWorldManagedBean.java
package org.spockprices.app.mbeans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class HelloWorldManagedBean implements Serializable {

	private static final long serialVersionUID = 887000498123573435L;

	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHello() {
		String greeting = null;
		
		if (name != null && !name.isEmpty()) {
			greeting = "Hello " + name;
		}
		
		return greeting;
	}
}

main_project/SpockPrices_webapp/src/main/java/org/spockprices/app/servlet/HelloWorldServlet.java
package org.spockprices.app.servlet;

import java.io.IOException;


import javax.ejb.EJB;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.spockprices.app.api.HelloWorldLocal;


@WebServlet("/HelloWorld")
public class HelloWorldServlet extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
	
	@EJB HelloWorldLocal helloWorld;
       
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getOutputStream().print(helloWorld.sayHello());
	}

}

main_project/SpockPrices_webapp/src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html">
 
<h:head>
    <title>JSF Demo</title>
</h:head>
<h:body>
    <h:outputScript name="jsf.js" library="javax.faces" target="body">
    </h:outputScript>
    <h1>JSF 2.1 Demo</h1>
    <h:form>
 
        <h:inputText id="name" value="#{helloWorldManagedBean.name}">
            <f:ajax render="helloTextOutput" />
        </h:inputText>
 
        <h:commandButton value="Say Hi via Ajax">
            <f:ajax execute="name" render="helloTextOutput" />
        </h:commandButton>
        
        <h:outputText id="helloTextOutput" value="#{helloWorldManagedBean.hello}" />
    </h:form>
 
</h:body>
</html>